/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as GoodbyeRouteImport } from './routes/goodbye'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProfileEnableTwoFactorRouteImport } from './routes/profile/enable-two-factor'
import { Route as ProfileChangePasswordRouteImport } from './routes/profile/change-password'
import { Route as LoginTwoFactorRouteImport } from './routes/login/two-factor'
import { Route as LoginSendPasswordResetRouteImport } from './routes/login/send-password-reset'
import { Route as LoginResetPasswordRouteImport } from './routes/login/reset-password'
import { Route as LoginOtpRouteImport } from './routes/login/otp'
import { Route as LoginBackupCodeRouteImport } from './routes/login/backup-code'
import { Route as ProfileConfirmTotpTotpURIBackupCodesRouteImport } from './routes/profile/confirm-totp.$totpURI.$backupCodes'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEnableTwoFactorRoute = ProfileEnableTwoFactorRouteImport.update({
  id: '/profile/enable-two-factor',
  path: '/profile/enable-two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChangePasswordRoute = ProfileChangePasswordRouteImport.update({
  id: '/profile/change-password',
  path: '/profile/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTwoFactorRoute = LoginTwoFactorRouteImport.update({
  id: '/login/two-factor',
  path: '/login/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSendPasswordResetRoute = LoginSendPasswordResetRouteImport.update({
  id: '/login/send-password-reset',
  path: '/login/send-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/login/reset-password',
  path: '/login/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/login/otp',
  path: '/login/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginBackupCodeRoute = LoginBackupCodeRouteImport.update({
  id: '/login/backup-code',
  path: '/login/backup-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileConfirmTotpTotpURIBackupCodesRoute =
  ProfileConfirmTotpTotpURIBackupCodesRouteImport.update({
    id: '/profile/confirm-totp/$totpURI/$backupCodes',
    path: '/profile/confirm-totp/$totpURI/$backupCodes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goodbye': typeof GoodbyeRoute
  '/todos': typeof TodosRoute
  '/login/backup-code': typeof LoginBackupCodeRoute
  '/login/otp': typeof LoginOtpRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/send-password-reset': typeof LoginSendPasswordResetRoute
  '/login/two-factor': typeof LoginTwoFactorRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/enable-two-factor': typeof ProfileEnableTwoFactorRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/confirm-totp/$totpURI/$backupCodes': typeof ProfileConfirmTotpTotpURIBackupCodesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goodbye': typeof GoodbyeRoute
  '/todos': typeof TodosRoute
  '/login/backup-code': typeof LoginBackupCodeRoute
  '/login/otp': typeof LoginOtpRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/send-password-reset': typeof LoginSendPasswordResetRoute
  '/login/two-factor': typeof LoginTwoFactorRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/enable-two-factor': typeof ProfileEnableTwoFactorRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/confirm-totp/$totpURI/$backupCodes': typeof ProfileConfirmTotpTotpURIBackupCodesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goodbye': typeof GoodbyeRoute
  '/todos': typeof TodosRoute
  '/login/backup-code': typeof LoginBackupCodeRoute
  '/login/otp': typeof LoginOtpRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/send-password-reset': typeof LoginSendPasswordResetRoute
  '/login/two-factor': typeof LoginTwoFactorRoute
  '/profile/change-password': typeof ProfileChangePasswordRoute
  '/profile/enable-two-factor': typeof ProfileEnableTwoFactorRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/confirm-totp/$totpURI/$backupCodes': typeof ProfileConfirmTotpTotpURIBackupCodesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/goodbye'
    | '/todos'
    | '/login/backup-code'
    | '/login/otp'
    | '/login/reset-password'
    | '/login/send-password-reset'
    | '/login/two-factor'
    | '/profile/change-password'
    | '/profile/enable-two-factor'
    | '/login'
    | '/profile'
    | '/profile/confirm-totp/$totpURI/$backupCodes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/goodbye'
    | '/todos'
    | '/login/backup-code'
    | '/login/otp'
    | '/login/reset-password'
    | '/login/send-password-reset'
    | '/login/two-factor'
    | '/profile/change-password'
    | '/profile/enable-two-factor'
    | '/login'
    | '/profile'
    | '/profile/confirm-totp/$totpURI/$backupCodes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/goodbye'
    | '/todos'
    | '/login/backup-code'
    | '/login/otp'
    | '/login/reset-password'
    | '/login/send-password-reset'
    | '/login/two-factor'
    | '/profile/change-password'
    | '/profile/enable-two-factor'
    | '/login/'
    | '/profile/'
    | '/profile/confirm-totp/$totpURI/$backupCodes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GoodbyeRoute: typeof GoodbyeRoute
  TodosRoute: typeof TodosRoute
  LoginBackupCodeRoute: typeof LoginBackupCodeRoute
  LoginOtpRoute: typeof LoginOtpRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
  LoginSendPasswordResetRoute: typeof LoginSendPasswordResetRoute
  LoginTwoFactorRoute: typeof LoginTwoFactorRoute
  ProfileChangePasswordRoute: typeof ProfileChangePasswordRoute
  ProfileEnableTwoFactorRoute: typeof ProfileEnableTwoFactorRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileConfirmTotpTotpURIBackupCodesRoute: typeof ProfileConfirmTotpTotpURIBackupCodesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/enable-two-factor': {
      id: '/profile/enable-two-factor'
      path: '/profile/enable-two-factor'
      fullPath: '/profile/enable-two-factor'
      preLoaderRoute: typeof ProfileEnableTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/change-password': {
      id: '/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof ProfileChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/two-factor': {
      id: '/login/two-factor'
      path: '/login/two-factor'
      fullPath: '/login/two-factor'
      preLoaderRoute: typeof LoginTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/send-password-reset': {
      id: '/login/send-password-reset'
      path: '/login/send-password-reset'
      fullPath: '/login/send-password-reset'
      preLoaderRoute: typeof LoginSendPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/reset-password': {
      id: '/login/reset-password'
      path: '/login/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/login/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/backup-code': {
      id: '/login/backup-code'
      path: '/login/backup-code'
      fullPath: '/login/backup-code'
      preLoaderRoute: typeof LoginBackupCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/confirm-totp/$totpURI/$backupCodes': {
      id: '/profile/confirm-totp/$totpURI/$backupCodes'
      path: '/profile/confirm-totp/$totpURI/$backupCodes'
      fullPath: '/profile/confirm-totp/$totpURI/$backupCodes'
      preLoaderRoute: typeof ProfileConfirmTotpTotpURIBackupCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GoodbyeRoute: GoodbyeRoute,
  TodosRoute: TodosRoute,
  LoginBackupCodeRoute: LoginBackupCodeRoute,
  LoginOtpRoute: LoginOtpRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
  LoginSendPasswordResetRoute: LoginSendPasswordResetRoute,
  LoginTwoFactorRoute: LoginTwoFactorRoute,
  ProfileChangePasswordRoute: ProfileChangePasswordRoute,
  ProfileEnableTwoFactorRoute: ProfileEnableTwoFactorRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileConfirmTotpTotpURIBackupCodesRoute:
    ProfileConfirmTotpTotpURIBackupCodesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
